api: 
  url: https://app.contrastsecurity.com/Contrast
  api_key: vgy5soZn15wnVPHH539pF8F7niofbl4N
  service_key: EMODO7ZF2MWAP798
  user_name: agent_142bb017-de7e-4af7-b5b9-f0782aa6d369@Ibm
agent: 
  service: 
    grpc: true
assess: 
  enable_lazy_tracking: false
application:
  group: "qroc : IBM Cloud SIEM for ISVs (broker only)"
